using System.ComponentModel;
using System.Globalization;
using System.Windows.Threading;
using DashDeck.Abstractions;
using DashDeck.Abstractions.Wpf;
using DashDeck.Host.Sensors;

namespace DashDeck.Host.Dash;

/// <summary>
/// Whatever a card is showing, however it gets it.
/// </summary>
/// <remarks>
/// The seam B4 has been asking for: a card used to be hard-wired to
/// <see cref="ObservableSignal"/>, which meant it could only ever show something the arbiter
/// schedules. Five perfectly good values — a heading, pitch, roll and two axes of G — were
/// catalogued, range-guarded and quality-tagged, and a card could not bind to any of them.
/// <para>
/// <b>The two sources are not equivalent and this interface does not pretend they are.</b> A
/// signal costs request budget on a shared serialised link; a sensor costs nothing, because
/// reading a magnetometer is not traffic on the OBD-II bus. That difference is what
/// <see cref="Footer"/> exists to keep visible — a card sourced from the tablet says so
/// rather than reporting an allocated rate it never asked for.
/// </para>
/// </remarks>
public interface ICardValue : IDisposable
{
    /// <summary>The number, in the catalog's own unit. May be NaN.</summary>
    double Value { get; }

    /// <summary>Unit symbol from whichever catalog defined it.</summary>
    string Unit { get; }

    /// <summary>How far this can be trusted, on the one scale everything uses.</summary>
    SignalQuality Quality { get; }

    /// <summary>True when there is a number worth drawing.</summary>
    bool IsUsable { get; }

    /// <summary>The card's footer line: an allocated rate, or where a sensor answered from.</summary>
    string Footer { get; }

    /// <summary>Raised when any of the above changed.</summary>
    event Action? Changed;
}

/// <summary>A vehicle signal, declared through the arbiter.</summary>
/// <remarks>
/// Thin, because <see cref="ObservableSignal"/> already does the work — declaring the demand,
/// marshalling readings onto the UI thread and rendering quality. This only adapts it.
/// </remarks>
public sealed class SignalCardValue : ICardValue
{
    private readonly ObservableSignal _signal;

    public SignalCardValue(IVehicleSignals signals, CardSpec spec)
    {
        _signal = new ObservableSignal(
            signals,
            spec.SignalId,
            spec.ParsedPriority,
            spec.RateHz,
            spec.Format);

        _signal.PropertyChanged += OnSignalChanged;
    }

    /// <inheritdoc />
    public event Action? Changed;

    /// <inheritdoc />
    public double Value => _signal.Value;

    /// <inheritdoc />
    public string Unit => _signal.Unit;

    /// <inheritdoc />
    public SignalQuality Quality => _signal.Quality;

    /// <inheritdoc />
    public bool IsUsable => _signal.IsUsable;

    /// <inheritdoc />
    public string Footer =>
        string.Create(CultureInfo.CurrentCulture, $"{_signal.EffectiveRateHz:0.##} Hz allocated");

    /// <inheritdoc />
    public void Dispose()
    {
        _signal.PropertyChanged -= OnSignalChanged;
        _signal.Dispose();
    }

    private void OnSignalChanged(object? sender, PropertyChangedEventArgs e) => Changed?.Invoke();
}

/// <summary>A tablet sensor, resolved truck-first.</summary>
/// <remarks>
/// Polled rather than subscribed, because <see cref="SensorService"/> is. The rate is a
/// display choice and nothing else — no vehicle traffic is generated by reading faster, so
/// this is picked for how a number looks moving rather than for what it costs.
/// <para>
/// It inherits ADR-0016 for free: a card bound to <c>attitude.heading</c> shows the truck's
/// heading the day one exists, and says <c>TRUCK</c> in its footer when it does, without the
/// card or the dashboard knowing anything about the switch.
/// </para>
/// </remarks>
public sealed class SensorCardValue : ICardValue
{
    /// <summary>Four times a second. A dash number that updates slower reads as frozen.</summary>
    private static readonly TimeSpan Poll = TimeSpan.FromMilliseconds(250);

    private readonly SensorService _sensors;
    private readonly string _sensorId;
    private readonly DispatcherTimer _timer;

    private SensorReading _reading;

    public SensorCardValue(SensorService sensors, string sensorId)
    {
        _sensors = sensors;
        _sensorId = sensorId;
        _reading = sensors.Read(sensorId);

        _timer = new DispatcherTimer(DispatcherPriority.Background) { Interval = Poll };
        _timer.Tick += (_, _) => Refresh();
        _timer.Start();
    }

    /// <inheritdoc />
    public event Action? Changed;

    /// <inheritdoc />
    public double Value => _reading.Value;

    /// <summary>The unit from the sensor catalog, which the reading itself does not carry.</summary>
    public string Unit { get; init; } = "";

    /// <inheritdoc />
    public SignalQuality Quality => _reading.Quality;

    /// <inheritdoc />
    public bool IsUsable => _reading.IsUsable;

    /// <summary>
    /// Where the value came from, not how fast it arrives.
    /// </summary>
    /// <remarks>
    /// A rate would be a lie here — nothing was allocated and nothing was asked of the truck.
    /// The source is the thing worth knowing, and it is the same string the compass shows:
    /// <c>TRUCK</c>, <c>TABLET · TRUE</c>, or <c>NOT LEVELLED</c>.
    /// </remarks>
    public string Footer => _reading.Source;

    /// <inheritdoc />
    public void Dispose() => _timer.Stop();

    private void Refresh()
    {
        var next = _sensors.Read(_sensorId);

        if (next == _reading)
        {
            return;
        }

        _reading = next;
        Changed?.Invoke();
    }
}

/// <summary>Builds the right kind of value for a card.</summary>
/// <remarks>
/// One place that knows both catalogs exist, so the dashboard and the cards do not have to.
/// When components start contributing sources of their own (F3), this is where a third kind
/// arrives — and nothing above it changes.
/// </remarks>
public sealed class CardValueFactory(IVehicleSignals signals, SensorService sensors)
{
    /// <summary>The vehicle signals, for anything that still needs them directly.</summary>
    public IVehicleSignals Signals => signals;

    /// <summary>The tablet sensors, resolved truck-first.</summary>
    public SensorService Sensors => sensors;

    /// <summary>
    /// Create a value for this card, or null when nothing can supply it.
    /// </summary>
    /// <remarks>
    /// Null rather than throwing: a card naming something neither catalog defines is kept and
    /// rendered as broken (ADR-0012), which needs the card to exist without a value behind it.
    /// </remarks>
    public ICardValue? Create(CardSpec spec, ValueChoice? choice)
    {
        if (choice is null)
        {
            return null;
        }

        return spec.ParsedSource switch
        {
            CardSource.Sensor => new SensorCardValue(sensors, spec.SignalId) { Unit = choice.Unit },
            _ => new SignalCardValue(signals, spec),
        };
    }
}
